version: '3.8'

services:
  static-website-example:
    build: 
      context: ./static-website-example
      dockerfile: Dockerfile
    container_name: static-website-example
    ports:
      - "8000:80"
    restart: always

  simple-webapp-color:
    build: 
      context: ./simple-webapp-color
      dockerfile: Dockerfile
    container_name: simple-webapp-color
    ports:
      - "5000:8080"
    environment:
      - APP_COLOR=blue
    restart: always
